### ISSUE TITLE
would it be possible to have a user control on which population is fixed as 0? 

### ISSUE THREAD

**Issue by mometRie** [jessekps/dexterMML#3]
https://github.com/dexter-psychometrics/dexterMML/blob/23ffa1c6433825ebeae55406ab5d72dfcfaefe3e/R/model_est.R#L190

**Comment by jessekps** [comment]
For the speed and stability of the estimation it turns out best to fix the largest group, so that is not something I would change. A reparametrisation afterwards is in principle possible, it would need a little work on the standard errors but not hard in principle. But it would add a little complexity to the user interface and I just don't see what purpose it would serve, so at the moment I'm not inclined to add this. The identification is an arbitrary choice, why do you want a different one?

**Comment by mometRie** [comment]
Dear Jesse, i follow your argument from the statistical point of view, but not from the practical examination setting. For example, when the exams are calibrated accross different college years and one is only interested to see the difference in means and standarddeviations in comparison for the first college-year, you would fix the first college year and only estimate the means and sd's for the following years. Ofcourse, you can use reparametrization but by this you might lose the information about the original population sd's and i think that's not really what you would like. ^Monika

**Comment by jessekps** [comment]
OK, I think I follow. For population comparison I would be much more inclined to use plausible values than an MML estimate it gives better results. But if you are interested in the MML population estimates, and the difference between means, why not rescale to your own preference by subtracting a mean and dividing by a standard deviation of the desired reference group? I don't understand how you would lose information about the population sd's since rescaling is exactly the added option you are asking for (i.e., fixing a different population will change all the sd's)
